"""Initial_Migration

Revision ID: 0568a3b5cf0d
Revises: 
Create Date: 2026-03-20 13:04:06.395815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0568a3b5cf0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeAdmin', sa.String(length=255), nullable=False),
    sa.Column('emailAdmin', sa.String(length=255), nullable=False),
    sa.Column('senhaAdmin', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeAluno', sa.String(length=255), nullable=False),
    sa.Column('emailAluno', sa.String(length=255), nullable=False),
    sa.Column('senhaAluno', sa.String(length=255), nullable=False),
    sa.Column('CPFAluno', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fases',
    sa.Column('id_fase', sa.Integer(), nullable=False),
    sa.Column('nome_fase', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_fase')
    )
    op.create_table('mentorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_create', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palestras_eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomeEvento', sa.String(length=255), nullable=False),
    sa.Column('dataInicial', sa.Date(), nullable=False),
    sa.Column('horaInicial', sa.Time(), nullable=False),
    sa.Column('dataFinal', sa.Date(), nullable=False),
    sa.Column('horaFinal', sa.Time(), nullable=False),
    sa.Column('nomePalestrante', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeProduto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomeProduto')
    )
    op.create_table('alunos_mentorias',
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('mentoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['mentoria_id'], ['mentorias.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'mentoria_id')
    )
    op.create_table('atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_atividade', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('plataforma', sa.String(length=50), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fase_id'], ['fases.id_fase'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mentoria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_mentoria'], ['mentorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reunioes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('id_mentoria', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['id_mentoria'], ['mentorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_produtos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'produto_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_produtos')
    op.drop_table('reunioes')
    op.drop_table('entregaveis')
    op.drop_table('atividades')
    op.drop_table('alunos_mentorias')
    op.drop_table('produtos')
    op.drop_table('palestras_eventos')
    op.drop_table('mentorias')
    op.drop_table('fases')
    op.drop_table('alunos')
    op.drop_table('administradores')
    # ### end Alembic commands ###
