"""Tabelas mentorias e entregaveis com id_mentoria.

Revision ID: 13207973045f
Revises: 69933695e6c9
Create Date: 2025-12-07 21:58:53.344915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13207973045f'
down_revision: Union[str, Sequence[str], None] = '69933695e6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_create', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_mentoria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_mentoria'], ['mentorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entregaveis')
    op.drop_table('mentorias')
    # ### end Alembic commands ###
