"""mentoria_isolation

Revision ID: 241c56316efa
Revises: 0568a3b5cf0d
Create Date: 2026-03-20 13:59:22.594874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '241c56316efa'
down_revision: Union[str, Sequence[str], None] = '0568a3b5cf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos_entregaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('entregavel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['entregavel_id'], ['entregaveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alunos', sa.Column('mentoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alunos', 'mentorias', ['mentoria_id'], ['id'])
    op.drop_column('entregaveis', 'status')
    op.drop_column('entregaveis', 'data_entrega')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entregaveis', sa.Column('data_entrega', sa.DATE(), nullable=True))
    op.add_column('entregaveis', sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.drop_column('alunos', 'mentoria_id')
    op.drop_table('alunos_entregaveis')
    # ### end Alembic commands ###
