"""Modificações nas tabelas.

Revision ID: 487d59c40c76
Revises: 1f23a91776d4
Create Date: 2025-12-10 16:52:12.114141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487d59c40c76'
down_revision: Union[str, Sequence[str], None] = '1f23a91776d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reunioes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('id_mentoria', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['id_mentoria'], ['mentorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reunioes')
    # ### end Alembic commands ###
