"""add table alunos_mentorias

Revision ID: 7cd3f46e1728
Revises: 487d59c40c76
Create Date: 2025-12-11 10:32:54.890032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd3f46e1728'
down_revision: Union[str, Sequence[str], None] = '487d59c40c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos_mentorias',
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('mentoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['mentoria_id'], ['mentorias.id'], ),
    sa.PrimaryKeyConstraint('aluno_id', 'mentoria_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos_mentorias')
    # ### end Alembic commands ###
