"""add status e data_entrega na tabela Entregavel_model.py

Revision ID: aaa63aaba984
Revises: 7cd3f46e1728
Create Date: 2025-12-11 20:45:12.153658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa63aaba984'
down_revision: Union[str, Sequence[str], None] = '7cd3f46e1728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entregaveis', sa.Column('status', sa.Enum('Pentende', 'Entregue'), nullable=True))
    op.add_column('entregaveis', sa.Column('data_entrega', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entregaveis', 'data_entrega')
    op.drop_column('entregaveis', 'status')
    # ### end Alembic commands ###
