"""add coluna(id_mentoria) na tabela de alunos.

Revision ID: cfafe026966a
Revises: 7ffe4c243982
Create Date: 2025-12-14 22:37:05.917356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfafe026966a'
down_revision: Union[str, Sequence[str], None] = '7ffe4c243982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('id_mentoria', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'alunos', 'mentorias', ['id_mentoria'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    op.drop_column('alunos', 'id_mentoria')
    # ### end Alembic commands ###
