"""modificação no status da tabela Entregavel_model.py para String ao invés de Enum.

Revision ID: f2f832ca238c
Revises: aaa63aaba984
Create Date: 2025-12-11 22:42:34.705372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2f832ca238c'
down_revision: Union[str, Sequence[str], None] = 'aaa63aaba984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entregaveis', 'status',
               existing_type=mysql.ENUM('Pentende', 'Entregue'),
               type_=sa.String(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entregaveis', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('Pentende', 'Entregue'),
               nullable=True)
    # ### end Alembic commands ###
